Add init command for project setup
mrzachnugent/react-native-reusables pull request #294
Opened 2024-12-19 14:23 UTC by unisol1020

## Description:

Add new CLI command 'init' to automate project setup. The command installs required dependencies.
Key features:
- Installs essential dependencies (nativewind, async-storage, etc.)
- Configures path aliases
- Copies utility files
- Supports overwriting existing files with confirmation prompt

## Tested Platforms:

- [x] Docs
- [x] Web

## Affected Apps/Packages:

- [apps/cli] - Added new init command
- [apps/docs] - Updated documentation for initial setup

Usage:
```bash
npx @react-native-reusables/cli@latest init [options]

2024-12-20 13:01 UTC, mrzachnugent commented
Hey @unisol1020 thanks for the PR.  I'll try to go over it this weekend.

I noticed that you are using a relative path to the starter-base template. Although that works locally it won't work as an npm package. You will need to add the package as a dependency in the package.json and use the path to the node_modules to use it.

2024-12-20 15:07 UTC, unisol1020 commented
Hi @mrzachnugent . Sry for this one. I never did it before, so i will check.

2024-12-20 16:49 UTC, versalarchitect commented
I just want to say, I'm very excited for this feature!

2024-12-21 16:10 UTC, mrzachnugent requested changes
Hey @unisol1020 Thanks for taking on this big feature. Let me know if anything needs more clarification.

2024-12-21 16:10 UTC, mrzachnugent commented on apps/docs/src/content/docs/getting-started/initial-setup.mdx
> +You can quickly set up your project using the React Native Reusables CLI. This will install all necessary dependencies and configure your project automatically.
Can you add that it is for an existing project:

`You can quickly set up your existing project using the React Native Reusables CLI. This command will install all necessary dependencies and automatically configure your project for you.
`

2024-12-21 16:10 UTC, mrzachnugent commented on apps/docs/src/content/docs/getting-started/initial-setup.mdx
> +  - RN Primitives Portal
Can you add links to each packages github/docs?

2024-12-21 16:10 UTC, mrzachnugent commented on apps/docs/src/content/docs/getting-started/initial-setup.mdx
> -  }
Can you keep this formatting?

2024-12-21 16:10 UTC, mrzachnugent commented on apps/docs/src/content/docs/getting-started/initial-setup.mdx
> -  }
Can you keep this formatting?

2024-12-21 16:10 UTC, mrzachnugent commented on apps/docs/src/content/docs/getting-started/initial-setup.mdx
> +colors: NAV_THEME.dark,
Can you keep the previous formatting?

2024-12-21 16:10 UTC, mrzachnugent commented on apps/docs/src/content/docs/getting-started/initial-setup.mdx
> -        setColorScheme(colorTheme);
Can you keep this formatting?

2024-12-21 16:10 UTC, mrzachnugent commented on apps/docs/src/content/docs/getting-started/initial-setup.mdx
> +); } `} />
Can you keep the previous formatting?

2024-12-22 10:09 UTC, unisol1020 commented
Hey @mrzachnugent. I will check. TY

2025-01-02 05:18 UTC, unisol1020 commented
Hey @mrzachnugent . Can u check if it looks good pls

2025-01-02 17:43 UTC, mrzachnugent approved these changes
@unisol1020 Thank you for contributing, Great job!

2025-01-02 17:45 UTC, merged

2025-01-02 19:07 UTC, unisol1020 commented
@mrzachnugent may I add dark theme/mode toggle to docs?

2025-01-03 15:54 UTC, mrzachnugent commented
@unisol1020

Do you mean adding the `<ThemeToggle />` component. In that case, you can add it. I think it would be best to add it in the `Extras` section.

<img width="1143" alt="Screenshot 2025-01-03 at 10 52 29 AM" src="https://github.com/user-attachments/assets/761f5b96-7205-4484-970c-3fad62d7304f" />