Fix Verbose useLayoutEffect on server render
mrzachnugent/react-native-reusables pull request #33
Opened 2024-02-05 21:43 UTC by the-simian

1. adds a line of code to prevent accessing function on server that causes verbose logging
2. adds a prettierrc.json that matches the existing code style

2024-02-05 21:45 UTC, the-simian commented
The toast component still works normally on the web-export, ios and android builds after this change
![image](https://github.com/mrzachnugent/react-native-reusables/assets/954596/756a7df0-fab0-4830-9eff-7ae51fe7a4fb)

2024-02-05 21:52 UTC, the-simian commented
This resolves https://github.com/mrzachnugent/react-native-reusables/issues/32

2024-02-06 00:22 UTC, mrzachnugent requested changes
Thank you for contributing!

Can you add this as a custom hook?

In `~/lib/useIsomorphicLayoutEffect.tsx`, can you add

```jsx
import * as React from 'react';

export const useIsomorphicLayoutEffect = typeof window !== 'undefined' ? useLayoutEffect : useEffect
```

And then use it here?

_FYI: If you were to use `import * as React from 'react'` here, you would get the typescript error: "Cannot assign to 'useLayoutEffect' because it is a read-only property"_

2024-02-06 02:41 UTC, the-simian commented
You bet, I think a custom hook is a better approach!

2024-02-06 02:54 UTC, the-simian commented
Update: I've added the hook for our own uses in situations where we'd call `useLayoutEffect` effect ourselves. I've left the existing shim in since its in a downstream module and I'm not sure how we'd get our hook in there. I can submit a PR to their repo directly in the future and we can then (probably) remove the shim.

2024-02-06 22:55 UTC, the-simian commented on lib/useIsomorphicLayoutEffect.tsx
> +  typeof window !== 'undefined' ? React.useLayoutEffect : React.useEffect;
File is now removed

2024-02-06 23:06 UTC, the-simian commented on components/ui/toast.tsx
> +
This comment has been updated to reference the issue I opened in `react-native-toast-message`

2024-02-06 23:07 UTC, the-simian commented
Here is the referenced issue in the other repo and I've made all the other requested changes:
https://github.com/calintamas/react-native-toast-message/issues/530

2024-02-07 14:03 UTC, mrzachnugent approved these changes
Great! Thank you

2024-02-07 14:03 UTC, merged